export enum ERROR_RESPONSE_MAP {
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    CONFLICT = 409,
    UNSUPPORTED_MEDIA_TYPE = 415,
    INTERNAL_SERVER = 500,
    LOST_CONNECTION = -1,
}