export enum SESSION_KEYS {
    USER = 'USER',
    AUTH_TOKEN = 'AUTH_TOKEN',
    API_ACCESS_TIMESTAMP = 'API_ACCESS_TIMESTAMP',
    APP_CONFIGURATION = 'APP_CONFIGURATION',
    ANONYMIZATION = 'ANONYMIZATION',
    REDIRECT_MODAL_DISPLAY = 'REDIRECT_MODAL_DISPLAY',
    TUMOR_BOARD_SELECTED_UUID = 'TUMOR_BOARD_SELECTED_UUID',
    TUMOR_BOARD_FILTER = 'TUMOR_BOARD_FILTER',
    PRESENTATION_RETURN_REFERENCE = 'PRESENTATION_RETURN_REFERENCE:',
}